# Load external directory
fpath=($ZDOTDIR/external $fpath)

# Source alias config
source "$XDG_CONFIG_HOME/zsh/aliases"

# Enable completion system
autoload -U compinit; compinit
_comp_options+=(globdots) # With hidden files
source "$DOTFILES/zsh/external/completion.zsh"

setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index

# Vim flavors
bindkey -v
export KEYTIMEOUT=1

# Vim mapping for completion
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Plugins
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source "$DOTFILES/zsh/external/bd.zsh"
source "$DOTFILES/zsh/scripts.sh"

# Prompt
eval "$(starship init zsh)"
