# Load external directory
fpath=($ZDOTDIR/plugins $fpath)

autoload -Uz cursor_mode && cursor_mode
# Enable completion system
autoload -U compinit; compinit
_comp_options+=(globdots) # With hidden files
source "$DOTFILES/zsh/plugins/completion.zsh"

setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

# Directory stack
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index


# Vim flavors
bindkey -v
export KEYTIMEOUT=1
bindkey "^?" backward-delete-char # Backspace fix

# Vim mapping for completion
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Sources
source "$XDG_CONFIG_HOME/zsh/aliases"
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source "$DOTFILES/zsh/plugins/bd.zsh"
source "$DOTFILES/zsh/scripts.sh"

# Prompt
eval "$(starship init zsh)"
